[package]
name = "ras-focus-pc"
version = "1.0.0"
description = "RasFocus PC - Website & App Blocker"
authors = ["Rasel"]
license = "MIT"
repository = ""
edition = "2021"

[[bin]]
name = "ras-focus-pc"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "webview-data-url"] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "stream"] }
url = "2"
